### ISSUE TITLE
关于我使用此启动器的报错

### ISSUE THREAD

**Issue by ETtttutu** [Goose-Bomb/GBCLV3#12]
System.IO.FileNotFoundException: 未能加载文件或程序集“System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   在 System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   在 System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   在 System.Reflection.RtFieldInfo.get_FieldType()
   在 StyletIoC.Creation.BuilderUpper.<>c__DisplayClass6_0.<GetExpression>b__0(FieldInfo x) 位置 C:\projects\stylet\Stylet\StyletIoC\Creation\BuilderUpper.cs:行号 42
   在 System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   在 System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 StyletIoC.Creation.BuilderUpper.GetExpression(Expression inputParameterExpression, ParameterExpression registrationContext, Type type) 位置 C:\projects\stylet\Stylet\StyletIoC\Creation\BuilderUpper.cs:行号 42
   在 StyletIoC.Internal.Creators.CreatorBase.CompleteExpressionFromCreator(Expression creator, ParameterExpression registrationContext) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Creators\CreatorBase.cs:行号 27
   在 StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:行号 114
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\SingletonRegistration.cs:行号 37
   在 StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClass6_0.<GetInstanceExpression>b__3(ParameterInfo x) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:行号 101
   在 System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   在 System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   在 StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:行号 112
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:行号 38
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator() 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:行号 30
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:行号 107
   在 StyletIoC.Internal.Container.Get[T](String key) 位置 C:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:行号 102
   在 Stylet.Bootstrapper`1.get_RootViewModel() 位置 C:\projects\stylet\Stylet\Bootstrapper.cs:行号 26
   在 Stylet.Bootstrapper`1.Launch() 位置 C:\projects\stylet\Stylet\Bootstrapper.cs:行号 92
   在 Stylet.BootstrapperBase.Start(String[] args) 位置 C:\projects\stylet\Stylet\BootstrapperBase.cs:行号 82
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

[Launcher Version: 3.0.3.41]

**Comment by Goose-Bomb** [comment]
你的系统安装或存在. NET Framework 4.7.2 运行环境吗？Window 10 1803及以上版本才有自带的。
