### ISSUE TITLE
启动器打不开

### ISSUE THREAD

**Issue by Hxyspace** [Goose-Bomb/GBCLV3#19]
最新版启动器打不开，双击没有任何反应

**Comment by Goose-Bomb** [comment]
系统版本？
试试删除GBCL.json设置文件或者放在一个空文件夹看能否运行。
如果不能运行很有可能是系统缺少必要的.NET Framwork运行环境

**Comment by Hxyspace** [comment]
版本3.0.7.59，放在新的空文件夹里还是打不开，之前3.0.5.50的版本能正常使用，所以应该不是运行环境的问题

**Comment by Goose-Bomb** [comment]
事实上，因为我将应用迁移到了.NET Core 3，所以有可能是缺少运行环境的问题
你可以尝试下载一个.NET Core 3.1 的 Desktop Runtime
[Download](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.0-windows-x64-installer)

> 版本3.0.7.59，放在新的空文件夹里还是打不开，之前3.0.5.50的版本能正常使用，所以应该不是运行环境的问题

**Comment by Goose-Bomb** [comment]
如果遇到打不开，请安装.net core 3.1桌面运行时
