### ISSUE TITLE
外置登录的HTTP协议问题

### ISSUE THREAD

**Issue by janblank499** [Goose-Bomb/GBCLV3#26]
我发现使用外置登录时会自动将验证服务器锁定为HTTPS协议，这极大的提升了安全性。但会使用户连接不上没有升级HTTPS协议的认证服务器

**Comment by Goose-Bomb** [comment]
事实上，这一点也是authlib-injector技术规范所要求的
见 [启动器技术规范] (https://github.com/yushijinhun/authlib-injector/wiki/%E5%90%AF%E5%8A%A8%E5%99%A8%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83)
如果不是普遍现象，我会维持现有的强制启用 HTTPS 设计。
