### ISSUE TITLE
莫名其妙无法打开

### ISSUE THREAD

**Issue by BaoZ1** [Goose-Bomb/GBCLV3#29]
这是第二次不知道为什么就打不开启动器了，不管是快捷方式还是exe本体，普通双击还是管理员身份运行，一点反应都没有的，重装一下就没有任何问题了。

**Comment by BaoZ1** [comment]
刚看了看下面那个关于自动更新bug的内容，我应该也是这个情况，但是后来重新下的最新版（3.0.9.104）同样无法打开，又换成3.0.8.81就很正常了。

**Comment by Goose-Bomb** [comment]
I believe it is still related to the #25 , next release it should be fixed. Unfortunately, you may need to do a manual update when next release is out.

我想这依然是和 #25 有关，下一个发行版应该能够修复。不过下一个版本可能只能通过手动下载更新了。

Now you could try to delete the temp directory: **_%TEMP%\.net\GBCL_** and replace the GBCL.exe with the latest 3.0.9.104 version and see if it could work.

现在你可以试试把 临时文件夹 **_%TEMP%\.net\GBCL_** 删除再用最新 3.0.9.104 版的exe覆盖，再看看可不可以启动

**Comment by Goose-Bomb** [comment]
你好，现在试试手动下载安装最新的 3.0.10.133 版本呢？应该已经解决这个问题了。
