### ISSUE TITLE
[ Suggestion ] Shaders Installation 🥺

### ISSUE THREAD

**Issue by vanja-san** [Goose-Bomb/GBCLV3#33]
Can you make the function of **installing shaders** through the launcher? 🤤

**Comment by Goose-Bomb** [comment]
Hi, I will be working on shaderpacks manager soon. Stay tuned!

**Comment by vanja-san** [comment]
> Hi, I will be working on shaderpacks manager soon. Stay tuned!

Wow! Pending!

**Comment by Goose-Bomb** [comment]
Hi, I've added the shaderpacks manager in the latest release, feel free to try it out!
