### ISSUE TITLE
[ Suggestion ] Create other game directories!

### ISSUE THREAD

**Issue by vanja-san** [Goose-Bomb/GBCLV3#35]
As I understand it, when downloading different versions, they are all downloaded to the same directory !? Maybe you should add the function of creating other directories? Just when changing the version, you have to switch mods and this is a little annoying! 😤

_I forget to add:_
_`Please accept my apologies for my poor English!`_ 😏

**Comment by Goose-Bomb** [comment]
Acutally, there is a **_Segregate Version_** options in **_Versions Management_**, by checking on this options, the mods, resourcepacks, shaders, saves, etc will be situated in _./minecraft/versions/{version_name}/_  instead of in the root directory (the _./minecraft/_) so different versions' files won't interfere with each other.

**Comment by vanja-san** [comment]
> 
> 
> Acutally, there is a **_Segregate Versions_** option in **_Versions Management_**, by checking on this option, the mods, resourcepacks, shaders, saves, etc of each version will be situated in _./minecraft/versions/{version_name}/_ instead of in the root directory (the _./minecraft/_) so different versions' files won't interfere with each other. This option will also change the behavior of **_Mods Management_** and **_Resourcepacks Management_**, they would only load the mods and packs of your currently selected version.

Oops, I apologize for the carelessness! 😅

**Comment by Goose-Bomb** [comment]
> > Acutally, there is a **_Segregate Versions_** option in **_Versions Management_**, by checking on this option, the mods, resourcepacks, shaders, saves, etc of each version will be situated in _./minecraft/versions/{version_name}/_ instead of in the root directory (the _./minecraft/_) so different versions' files won't interfere with each other. This option will also change the behavior of **_Mods Management_** and **_Resourcepacks Management_**, they would only load the mods and packs of your currently selected version.
> 
> Oops, I apologize for the carelessness! 😅

It's my fault actually... I should have made a user guide or something. Unfortunately I'm busy doing my graduation project...I could start to work on the documentations when I have more time.
