### ISSUE TITLE
Drag&Drop

### ISSUE THREAD

**Issue by vanja-san** [Goose-Bomb/GBCLV3#37]
Make it possible to copy mods with drag & drop!
So far, files are completely moved from one folder to another. In other words, they are deleted from source folder.
### **This is GIF (click):**
![2020-03-20-20-19-31](https://user-images.githubusercontent.com/7201687/77167727-29d57280-6ae9-11ea-83e6-18b3d971151b.gif)

**Comment by Goose-Bomb** [comment]
Yeah, I could add an option to control whether it will move the files or copy the files.
