### ISSUE TITLE
BUG👻 UTF-8 with BOM

### ISSUE THREAD

**Issue by KisaragiSaya** [Goose-Bomb/GBCLV3#42]
1.[UTF-8 with BOM]格式文件❌
2.[modinfo]读取失败（包含1👆）
![Screenshot_1584962140](https://user-images.githubusercontent.com/25012170/77311257-b88cfe00-6d3a-11ea-8fdd-610a642b0d0c.png)
e.g:
![Screenshot_1584961346](https://user-images.githubusercontent.com/25012170/77311105-78c61680-6d3a-11ea-828d-bb5d6bae23d2.png)
![Screenshot_1584961454](https://user-images.githubusercontent.com/25012170/77311108-7b287080-6d3a-11ea-8e42-45d74ef7ec60.png)

**Comment by KisaragiSaya** [comment]
这个问题你关早了，你只修复了我说的第一点，第二点你没改😅

可能之前我只截了个图，你没有看明白，这里我详细说一下
有部分mod的modinfo你会读取失败并且没做异常处理
先不谈为什么会读取失败，单就这种非致命错误捕获（提示）一下就可以了
不应该程序直接崩溃退出

比如截图里面我选中的

这个mod（Hwyla）
至于读取失败的原因，你可以看下它的 "authors" 节点就明白了
人家作者可不止一个😂😂😂

参考：[Hwyla-fabric-1.15.2-1.9.20-71.jar.zip](https://github.com/Goose-Bomb/GBCLV3/files/4387293/Hwyla-fabric-1.15.2-1.9.20-71.jar.zip)

**Comment by Goose-Bomb** [comment]
草，我看了几个frbric mod authers 字段都是list of strings 我还以为是fabric mod info都是统一这种format呢，没想到还有这一出。。。这些瓜批 mod作者就不能统一下吗。。。也罢
我直接扔到一个大try catch block里好了

**Comment by Goose-Bomb** [comment]
没有标准的话我也没办法处理所有的mod的 info json... 这种 heterogeneous json 搞起来还蛮恶心的

**Comment by KisaragiSaya** [comment]
这种要做简单点就是取出所有“authors”子节点
如果不是string就去读下面有没有“neme”
有就加入，“contact”或其他信息忽略
基本上也就这两种格式了，不太可以出现其他种类的了

当然不处理这种类型也行😂😂😂😂😂
