### ISSUE TITLE
清空资源包问题

### ISSUE THREAD

**Issue by KisaragiSaya** [Goose-Bomb/GBCLV3#43]
options.txt
从1.13版本开始格式就已经是：🙄
resourcePacks:["vanilla","file/Diamond War150322.zip","file/VoxelMap Skin §e1.X.X.zip"]
而启动器依然是这种格式存取：😅
resourcePacks:["Diamond War150322.zip","VoxelMap Skin §e1.X.X.zip"]

所以出现无限清空资源包配置的情况

这个问题我第一次接触这个启动器时就发现了，然后自己修改了一下就没管了
但是我很诧异这么久了竟然一直没人提😂

**Comment by Goose-Bomb** [comment]
应该是这样：游戏仍然支持从老格式选取加载资源包，而且在游戏中如果不修改资源包顺序的话也不会重新写入options.txt 所以只要不在游戏中改资源包那么就一直能用...怪不得没有发现这个问题。
已经修改了。
