### ISSUE TITLE
Can you make a setup file?

### ISSUE THREAD

**Issue by JustExe** [Goose-Bomb/GBCLV3#62]
Can you create a setup that will automatically install all the requirements and the launcher as open source?
I'm very new in this stuff, it may be simple for you, but I'd be grateful if you do.

**Comment by Goose-Bomb** [comment]
This launcher can run as a stand-alone executable file, as long as your system has proper .NET Core 3.1 desktop runtime installed. As for the runtime, you can easily get the installer from here: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.14-windows-x64-installer

**Comment by Goose-Bomb** [comment]
Sorry, maybe I get you wrong. You mean setting up the development environment on your system?
