### ISSUE TITLE
I couldn't run the contents of the debug folder on another computer?

### ISSUE THREAD

**Issue by YT-Dragon** [Goose-Bomb/GBCLV3#63]
I installed net core 3.1 on the other computer but when I click on the exe extension nothing happens? Windows 10 64bit on 2 systems.

**Comment by Goose-Bomb** [comment]
If you want the program to run on another computer, you need to **publish** the program in single file mode so every dependencies (the dlls) are bundled into a single .exe file.
See https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file for details.

**Comment by Goose-Bomb** [comment]
Also, maybe the program have dependencies in the .NET Core SDKs (not the runtime) when compiled in Debug mode, so if there's no or wrong version of SDKs on the other computer, it may not able to run.
Sorry I've never tried to run **Debug** programs outside my development environment before, so I'm unclear why. If you just want the program to run on another computer, I believe `publish` is what you need.
